services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "9000:9000"
    env_file:
      - ./gateway/.env
    networks:
      - ai-network
    volumes:
      - ./gateway:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload

  titanic-service:
    build:
      context: ./titanic-service
      dockerfile: Dockerfile
    container_name: titanic
    ports:
      - "9001:9001"
    env_file:
      - ./titanic-service/.env
    networks:
      - ai-network
    volumes:
      - ./titanic-service:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9001 --reload

  crime-service:
    build:
      context: ./crime-service
      dockerfile: Dockerfile
    container_name: crime
    ports:
      - "9002:9002"
    env_file:
      - ./crime-service/.env
    networks:
      - ai-network
    volumes:
      - ./crime-service:/app
      - /c/Users/bitcamp/Documents/demo/v2/ai-server/crime-service/app/stored_map:/app/stored_map
      - /c/Users/bitcamp/Documents/demo/v2/ai-server/crime-service/app/up_data:/app/up_data
      - /c/Users/bitcamp/Documents/demo/v2/ai-server/crime-service/app/stored_data:/app/stored_data
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9002 --reload

  nlp-service:
    build:
      context: ./nlp-service
      dockerfile: Dockerfile
    container_name: nlp
    ports:
      - "9004:9004"
    env_file:
      - ./nlp-service/.env
    networks:
      - ai-network
    volumes:
      - ./nlp-service:/app
      - ./nlp-service/app/original:/app/original
      - ./nlp-service/app/output:/app/output
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9004 --reload

  tf-service:
    build:
      context: ./tf-service
      dockerfile: Dockerfile
    container_name: tf
    ports:
      - "9005:9005"
    env_file:
      - ./tf-service/.env
    networks:
      - ai-network
    volumes:
      - ./tf-service:/app
      - ./tf-service/uploads:/app/uploads
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9005 --reload

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat
    ports:
      - "9006:9006"
    env_file:
      - ./chat-service/.env
    networks:
      - ai-network
    volumes:
      - ./chat-service:/app
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 9006 --reload


networks:
  ai-network:
    driver: bridge
  
